language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

install:
    - composer install

env:
    - DB=mysql
    - DB=pgsql POSTGRESQL_VERSION=9.1
    - DB=pgsql POSTGRESQL_VERSION=9.2
    - DB=pgsql POSTGRESQL_VERSION=9.3
    - DB=pgsql POSTGRESQL_VERSION=9.4

before_script:
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database qcubed;'; mysql -u root qcubed < vendor/qcubed/orm/test/db/mysql_innodb.sql; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then createdb qcubed -U postgres; psql -d qcubed -f vendor/qcubed/orm/test/db/pgsql.sql -U postgres; fi"

script:
    - ./vendor/bin/phpunit -c ./test/phpunit.xml --coverage-clover ./build/logs/clover.xml

# code coverage
addons:
    code_climate:
        repo_token: 814dfe2ee0ae6198e43e566e32ab85f40379b5abe06cd52b1f6a24e92b5de883

# code coverage
after_script:
    - vendor/bin/test-reporter

sudo: false

matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
    - php: hhvm
      env: DB=pgsql POSTGRESQL_VERSION=9.4 # driver currently unsupported by HHVM

