<?php
/**
 *
 * Part of the QCubed PHP framework.
 *
 * @license MIT
 *
 */

namespace QCubed\FormState;

/**
 * Interface HandlerInterface
 *
 * Implements the interface for formstates. This is currently a static object.
 *
 * TODO: Change this to be a service of the singleton application object.
 *
 * @package QCubed\FormState
 */
interface HandlerInterface {

    /**
     * Saves the given form state off for later recall. The form state is a serialized version of the form object,
     * so could be quite big.
     *
     * Returns a token that can be used to retrieve the state later.
     *
     * @param $strFormState
     * @param $blnBackButtonFlag
     * @return mixed
     */
    public static function save($strFormState, $blnBackButtonFlag);

    /**
     * Returns the serialized form state, give a token that was generated by the save() function above.
     * @param $strPostDataState
     * @return mixed
     */
    public static function load($strPostDataState);
}